from .medicoSerializer import MedicoSerializer
from .usuarioSerializer import UsuarioSerializer
from .pacienteSerializer import PacienteSerializer
from .signosSerializer import SignosVitalesSerializer
from .histclinicaserializer import HistoriaClinicaSeralizer
from .familiarSerializer import FamiliarSerializer

